GET http://localhost:7000/api/v1/lesson/content/645255491f2d691aa5a8adb3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTI0ODg5NTVhYTM3MTgwOGU3NjZjMCIsImlhdCI6MTY4MzY5NzY2MCwiZXhwIjoxNjg0MzAyNDYwfQ.Rzbgunndo8vZYSW7oO7UzD1WH5OnK2sr3Xuh9-jS4O0


###
GET http://localhost:7000/api/v1/lesson/content/645255491f2d691aa5a8adb3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTI0ODg5NTVhYTM3MTgwOGU3NjZjMCIsImlhdCI6MTY4MzY5NzY2MCwiZXhwIjoxNjg0MzAyNDYwfQ.Rzbgunndo8vZYSW7oO7UzD1WH5OnK2sr3Xuh9-jS4O0
